#include "stdafx.h"
#include "Attribute.h"

const int Attribute::AttributeNames [] =
{
	IDS_ATTRIBUTE_NAME_GENERIC_MAXHEALTH,		
	IDS_ATTRIBUTE_NAME_GENERIC_FOLLOWRANGE,			
	IDS_ATTRIBUTE_NAME_GENERIC_KNOCKBACKRESISTANCE,
	IDS_ATTRIBUTE_NAME_GENERIC_MOVEMENTSPEED,		
	IDS_ATTRIBUTE_NAME_GENERIC_ATTACKDAMAGE,
	IDS_ATTRIBUTE_NAME_HORSE_JUMPSTRENGTH,
	IDS_ATTRIBUTE_NAME_ZOMBIE_SPAWNREINFORCEMENTS,
};

int Attribute::getName(eATTRIBUTE_ID id)
{
	return AttributeNames[id];
}