#pragma once

#include "AddEntityPacket.h"
#include "AddGlobalEntityPacket.h"
#include "AddMobPacket.h"
#include "AddPaintingPacket.h"
#include "AddPlayerPacket.h"
#include "AnimatePacket.h"
#include "AwardStatPacket.h"
#include "BlockRegionUpdatePacket.h"
#include "ChatPacket.h"
#include "ChunkTilesUpdatePacket.h"
#include "ChunkVisibilityPacket.h"
#include "ComplexItemDataPacket.h"
#include "ContainerAckPacket.h"
#include "ContainerClickPacket.h"
#include "ContainerClosePacket.h"
#include "ContainerOpenPacket.h"
#include "ContainerSetContentPacket.h"
#include "ContainerSetDataPacket.h"
#include "ContainerSetSlotPacket.h"
#include "DisconnectPacket.h"
#include "EntityActionAtPositionPacket.h"
#include "EntityEventPacket.h"
#include "ExplodePacket.h"
#include "GameEventPacket.h"
#include "InteractPacket.h"
#include "KeepAlivePacket.h"
#include "LevelEventPacket.h"
#include "LoginPacket.h"
#include "MoveEntityPacket.h"
#include "MoveEntityPacketSmall.h"
#include "MovePlayerPacket.h"
#include "Packet.h"
#include "PacketListener.h"
#include "PlayerActionPacket.h"
#include "PlayerCommandPacket.h"
#include "PlayerInputPacket.h"
#include "PreLoginPacket.h"
#include "RemoveEntitiesPacket.h"
#include "RespawnPacket.h"

#include "SetCarriedItemPacket.h"
#include "SetEntityDataPacket.h"
#include "SetEntityMotionPacket.h"
#include "SetEquippedItemPacket.h"
#include "SetHealthPacket.h"
#include "SetEntityLinkPacket.h"
#include "SetSpawnPositionPacket.h"
#include "SetTimePacket.h"
#include "SignUpdatePacket.h"
#include "TakeItemEntityPacket.h"
#include "TeleportEntityPacket.h"
#include "TileEventPacket.h"
#include "TileUpdatePacket.h"
#include "UseItemPacket.h"

// 1.8.2 Added
#include "AddExperienceOrbPacket.h"
#include "GetInfoPacket.h"
#include "PlayerInfoPacket.h"
#include "RemoveMobEffectPacket.h"
#include "SetCreativeModeSlotPacket.h"
#include "SetExperiencePacket.h"
#include "UpdateMobEffectPacket.h"

// 1.0.1 Added
#include "ContainerButtonClickPacket.h"
#include "TileEntityDataPacket.h"

// 1.1 Added (TU9)
#include "CustomPayloadPacket.h"

// 1.2.3
#include "RotateHeadPacket.h"

// 1.3.2
#include "ChatAutoCompletePacket.h"
#include "ClientCommandPacket.h"
#include "ClientInformationPacket.h"
#include "ClientProtocolPacket.h"
#include "LevelSoundPacket.h"
#include "PlayerAbilitiesPacket.h"
#include "ServerAuthDataPacket.h"
#include "TileDestructionPacket.h"

// 1.6.4
#include "LevelParticlesPacket.h"
#include "SetDisplayObjectivePacket.h"
#include "SetObjectivePacket.h"
#include "SetPlayerTeamPacket.h"
#include "SetScorePacket.h"
#include "TileEditorOpenPacket.h"
#include "UpdateAttributesPacket.h"

// 4J Added
#include "CraftItemPacket.h"
#include "TradeItemPacket.h"
#include "DebugOptionsPacket.h"
#include "ServerSettingsChangedPacket.h"
#include "TexturePacket.h"
#include "TextureAndGeometryPacket.h"
#include "ChunkVisibilityAreaPacket.h"
#include "UpdateProgressPacket.h"
#include "TextureChangePacket.h"
#include "TextureAndGeometryChangePacket.h"
#include "UpdateGameRuleProgressPacket.h"
#include "KickPlayerPacket.h"
#include "XZPacket.h"
#include "GameCommandPacket.h"

