#pragma once

// 4J-PB - if you change this, you need to update SoundEngine::wchSoundNames[]
enum eSOUND_TYPE
{
	eSoundType_MOB_CHICKEN_AMBIENT,
	eSoundType_MOB_CHICKEN_HURT,
	eSoundType_MOB_CHICKENPLOP,
	eSoundType_MOB_COW_AMBIENT,
	eSoundType_MOB_COW_HURT,
	eSoundType_MOB_PIG_AMBIENT,
	eSoundType_MOB_PIG_DEATH,
	eSoundType_MOB_SHEEP_AMBIENT,
	eSoundType_MOB_WOLF_GROWL,
	eSoundType_MOB_WOLF_WHINE,
	eSoundType_MOB_WOLF_PANTING,
	eSoundType_MOB_WOLF_BARK,
	eSoundType_MOB_WOLF_HURT,
	eSoundType_MOB_WOLF_DEATH,
	eSoundType_MOB_WOLF_SHAKE,
	eSoundType_MOB_BLAZE_BREATHE,
	eSoundType_MOB_BLAZE_HURT,
	eSoundType_MOB_BLAZE_DEATH,
	eSoundType_MOB_GHAST_MOAN,
	eSoundType_MOB_GHAST_SCREAM,
	eSoundType_MOB_GHAST_DEATH,
	eSoundType_MOB_GHAST_FIREBALL,
	eSoundType_MOB_GHAST_CHARGE,
	eSoundType_MOB_ENDERMEN_IDLE,
	eSoundType_MOB_ENDERMEN_HIT,
	eSoundType_MOB_ENDERMEN_DEATH,
	eSoundType_MOB_ENDERMEN_PORTAL,
	eSoundType_MOB_ZOMBIEPIG_AMBIENT,
	eSoundType_MOB_ZOMBIEPIG_HURT,
	eSoundType_MOB_ZOMBIEPIG_DEATH,
	eSoundType_MOB_ZOMBIEPIG_ZPIGANGRY,
	eSoundType_MOB_SILVERFISH_AMBIENT,
	eSoundType_MOB_SILVERFISH_HURT,
	eSoundType_MOB_SILVERFISH_DEATH,
	eSoundType_MOB_SILVERFISH_STEP,
	eSoundType_MOB_SKELETON_AMBIENT,
	eSoundType_MOB_SKELETON_HURT,
	eSoundType_MOB_SPIDER_AMBIENT,
	eSoundType_MOB_SPIDER_DEATH,
	eSoundType_MOB_SLIME,
	eSoundType_MOB_SLIME_ATTACK,
	eSoundType_MOB_CREEPER_HURT,
	eSoundType_MOB_CREEPER_DEATH,
	eSoundType_MOB_ZOMBIE_AMBIENT,
	eSoundType_MOB_ZOMBIE_HURT,
	eSoundType_MOB_ZOMBIE_DEATH,
	eSoundType_MOB_ZOMBIE_WOOD,
	eSoundType_MOB_ZOMBIE_WOOD_BREAK,
	eSoundType_MOB_ZOMBIE_METAL,
	eSoundType_MOB_MAGMACUBE_BIG,
	eSoundType_MOB_MAGMACUBE_SMALL,
	eSoundType_MOB_CAT_PURR,
	eSoundType_MOB_CAT_PURREOW,
	eSoundType_MOB_CAT_MEOW,
	eSoundType_MOB_CAT_HIT,
//	eSoundType_MOB_IRONGOLEM_THROW,
//	eSoundType_MOB_IRONGOLEM_HIT,
//	eSoundType_MOB_IRONGOLEM_DEATH,
//	eSoundType_MOB_IRONGOLEM_WALK,
	eSoundType_RANDOM_BOW,
	eSoundType_RANDOM_BOW_HIT,
	eSoundType_RANDOM_EXPLODE,
	eSoundType_RANDOM_FIZZ,	
	eSoundType_RANDOM_POP,
	eSoundType_RANDOM_FUSE,
	eSoundType_RANDOM_DRINK,
	eSoundType_RANDOM_EAT,
	eSoundType_RANDOM_BURP,
	eSoundType_RANDOM_SPLASH,
	eSoundType_RANDOM_CLICK,
	eSoundType_RANDOM_GLASS,
	eSoundType_RANDOM_ORB,
	eSoundType_RANDOM_BREAK,
	eSoundType_RANDOM_CHEST_OPEN,
	eSoundType_RANDOM_CHEST_CLOSE,
	eSoundType_RANDOM_DOOR_OPEN,
	eSoundType_RANDOM_DOOR_CLOSE,
	eSoundType_AMBIENT_WEATHER_RAIN,
	eSoundType_AMBIENT_WEATHER_THUNDER,
	eSoundType_AMBIENT_CAVE_CAVE,
#ifdef _XBOX
	eSoundType_AMBIENT_CAVE_CAVE2, //- fixed version of eSoundType_CAVE_CAVE, without the two 192k sounds
#endif
	eSoundType_PORTAL_PORTAL,
	// 4J-PB - adding some that were still text in the code
	eSoundType_PORTAL_TRIGGER,
	eSoundType_PORTAL_TRAVEL,

	eSoundType_FIRE_IGNITE,
	eSoundType_FIRE_FIRE,
	eSoundType_DAMAGE_HURT,
	eSoundType_DAMAGE_FALL_SMALL,
	eSoundType_DAMAGE_FALL_BIG,
	eSoundType_NOTE_HARP,
	eSoundType_NOTE_BD,
	eSoundType_NOTE_SNARE,
	eSoundType_NOTE_HAT,
	eSoundType_NOTE_BASSATTACK,
	eSoundType_TILE_PISTON_IN,
	eSoundType_TILE_PISTON_OUT,
	eSoundType_LIQUID_WATER,
	eSoundType_LIQUID_LAVA_POP,
	eSoundType_LIQUID_LAVA,
	eSoundType_STEP_STONE,
	eSoundType_STEP_WOOD,
	eSoundType_STEP_GRAVEL,
	eSoundType_STEP_GRASS,
	eSoundType_STEP_METAL,
	eSoundType_STEP_CLOTH,
	eSoundType_STEP_SAND,
	// soundbank 2
	eSoundType_MOB_ENDERDRAGON_END,
	eSoundType_MOB_ENDERDRAGON_GROWL,
	eSoundType_MOB_ENDERDRAGON_HIT,
	eSoundType_MOB_ENDERDRAGON_MOVE,
	eSoundType_MOB_IRONGOLEM_THROW,
	eSoundType_MOB_IRONGOLEM_HIT,
	eSoundType_MOB_IRONGOLEM_DEATH,
	eSoundType_MOB_IRONGOLEM_WALK,

	// TU14
	eSoundType_DAMAGE_THORNS,
	eSoundType_RANDOM_ANVIL_BREAK,
	eSoundType_RANDOM_ANVIL_LAND,
	eSoundType_RANDOM_ANVIL_USE,
	eSoundType_MOB_VILLAGER_HAGGLE,
	eSoundType_MOB_VILLAGER_IDLE,
	eSoundType_MOB_VILLAGER_HIT,
	eSoundType_MOB_VILLAGER_DEATH,
	eSoundType_MOB_VILLAGER_YES,
	eSoundType_MOB_VILLAGER_NO,
	eSoundType_MOB_ZOMBIE_INFECT,
	eSoundType_MOB_ZOMBIE_UNFECT,
	eSoundType_MOB_ZOMBIE_REMEDY,
	eSoundType_STEP_SNOW,
	eSoundType_STEP_LADDER,
	eSoundType_DIG_CLOTH,
	eSoundType_DIG_GRASS,
	eSoundType_DIG_GRAVEL,
	eSoundType_DIG_SAND,
	eSoundType_DIG_SNOW,
	eSoundType_DIG_STONE,
	eSoundType_DIG_WOOD,

	// 1.6.4
	eSoundType_FIREWORKS_LAUNCH,
	eSoundType_FIREWORKS_BLAST,
	eSoundType_FIREWORKS_BLAST_FAR,
	eSoundType_FIREWORKS_LARGE_BLAST,
	eSoundType_FIREWORKS_LARGE_BLAST_FAR,
	eSoundType_FIREWORKS_TWINKLE,
	eSoundType_FIREWORKS_TWINKLE_FAR,

	eSoundType_MOB_BAT_IDLE,
	eSoundType_MOB_BAT_HURT,
	eSoundType_MOB_BAT_DEATH,
	eSoundType_MOB_BAT_TAKEOFF,


	eSoundType_MOB_WITHER_SPAWN,
	eSoundType_MOB_WITHER_IDLE,	//"mob.wither.idle";
	eSoundType_MOB_WITHER_HURT, //"mob.wither.hurt";
	eSoundType_MOB_WITHER_DEATH,//"mob.wither.death";
	eSoundType_MOB_WITHER_SHOOT,//"mob.wither.shoot";

	eSoundType_MOB_COW_STEP,
	eSoundType_MOB_CHICKEN_STEP,
	eSoundType_MOB_PIG_STEP,
	eSoundType_MOB_ENDERMAN_STARE,
	eSoundType_MOB_ENDERMAN_SCREAM,
	eSoundType_MOB_SHEEP_SHEAR,
	eSoundType_MOB_SHEEP_STEP,
	eSoundType_MOB_SKELETON_DEATH,
	eSoundType_MOB_SKELETON_STEP,
	eSoundType_MOB_SPIDER_STEP,
	eSoundType_MOB_WOLF_STEP,
	eSoundType_MOB_ZOMBIE_STEP,
	eSoundType_LIQUID_SWIM,
	eSoundType_MOB_HORSE_LAND,
	eSoundType_MOB_HORSE_ARMOR,
	eSoundType_MOB_HORSE_LEATHER,
	eSoundType_MOB_HORSE_ZOMBIE_DEATH,
	eSoundType_MOB_HORSE_SKELETON_DEATH,
	eSoundType_MOB_HORSE_DONKEY_DEATH,
	eSoundType_MOB_HORSE_DEATH,
	eSoundType_MOB_HORSE_ZOMBIE_HIT,
	eSoundType_MOB_HORSE_SKELETON_HIT,
	eSoundType_MOB_HORSE_DONKEY_HIT,
	eSoundType_MOB_HORSE_HIT,
	eSoundType_MOB_HORSE_ZOMBIE_IDLE,
	eSoundType_MOB_HORSE_SKELETON_IDLE,
	eSoundType_MOB_HORSE_DONKEY_IDLE,
	eSoundType_MOB_HORSE_IDLE,
	eSoundType_MOB_HORSE_DONKEY_ANGRY,
	eSoundType_MOB_HORSE_ANGRY,
	eSoundType_MOB_HORSE_GALLOP,
	eSoundType_MOB_HORSE_BREATHE,
	eSoundType_MOB_HORSE_WOOD,
	eSoundType_MOB_HORSE_SOFT,
	eSoundType_MOB_HORSE_JUMP,
	eSoundType_MOB_WITCH_IDLE,
	eSoundType_MOB_WITCH_HURT,
	eSoundType_MOB_WITCH_DEATH,
	eSoundType_MOB_SLIME_BIG,
	eSoundType_MOB_SLIME_SMALL,
	eSoundType_EATING,
	eSoundType_RANDOM_LEVELUP,

	eSoundType_FIRE_NEWIGNITE,

	eSoundType_MAX
};

// 4J-PB - if you change this, you need to update SoundEngine::wchUISoundNames[]
enum ESoundEffect
{
	eSFX_Back,
	eSFX_Craft,
	eSFX_CraftFail,
	eSFX_Focus,
	eSFX_Press,
	eSFX_Scroll,
	eSFX_MAX
};

enum eMATERIALSOUND_TYPE
{
	eMaterialSoundType_STONE,
	eMaterialSoundType_WOOD,	
	eMaterialSoundType_GRAVEL,
	eMaterialSoundType_GRASS,
	eMaterialSoundType_METAL,
	eMaterialSoundType_GLASS,
	eMaterialSoundType_CLOTH,
	eMaterialSoundType_SAND,
	eMaterialSoundType_SNOW,
	eMaterialSoundType_LADDER,
	eMaterialSoundType_ANVIL,
};

/*
enum eSOUND_TYPE
{
L"mob.chicken",
L"mob.chickenhurt",
L"mob.chickenplop",

L"mob.cow",
L"mob.cowhurt",

L"mob.pig",
L"mob.pigdeath",

L"mob.sheep",

L"mob.wolf.growl",
L"mob.wolf.whine",
L"mob.wolf.panting",
L"mob.wolf.bark",
L"mob.wolf.hurt",
L"mob.wolf.death",
L"mob.wolf.shake",

L"mob.blaze.breathe",
L"mob.blaze.hit",
L"mob.blaze.death",

L"mob.ghast.moan",
L"mob.ghast.scream",
L"mob.ghast.death",
L"mob.ghast.fireball",
	L"mob.ghast.charge",

	L"mob.endermen.idle",
	L"mob.endermen.hit",
	L"mob.endermen.death",
	L"mob.endermen.portal",

	L"mob.zombiepig.zpig",
	L"mob.zombiepig.zpighurt",
	L"mob.zombiepig.zpigdeath",
	L"mob.zombiepig.zpigangry",

	L"mob.silverfish.say",
	L"mob.silverfish.hit",
	L"mob.silverfish.kill",
	L"mob.silverfish.step",

	L"mob.skeleton",
	L"mob.skeleton.hurt",

	L"mob.spider",
	L"mob.spiderdeath",

	L"mob.slime",
	L"mob.slimeattack",

	L"mob.creeper",
	L"mob.creeperdeath",

	L"mob.zombie",
	L"mob.zombiehurt",
	L"mob.zombiedeath",
	L"mob.zombie.wood",
	L"mob.zombie.woodbreak",
	L"mob.zombie.metal",

	L"mob.magmacube.big",
	L"mob.magmacube.small",

	L"random.bow",
	L"random.bowhit",
	L"random.explode",
	L"random.fizz",	
	L"random.pop",
	L"random.fuse",
	L"random.drink",
	L"random.eat",
	L"random.burp",
	L"random.splash",
	L"random.click",
	L"random.glass",
	L"random.orb",
	L"random.break",
	L"random.chestopen",
	L"random.chestclosed",
	L"random.door_open",
	L"random.door_close",

	L"ambient.weather.rain",
	L"ambient.weather.thunder",

	L"ambient.cave.cave",

	L"portal.portal",

	L"fire.ignite",
	L"fire.fire",

	L"damage.hurtflesh",
	L"damage.fallsmall",
	L"damage.fallbig",

	L"note.harp",
	L"note.bd",
	L"note.snare",
	L"note.hat",
	L"note.bassattack",

	L"tile.piston.in",
	L"tile.piston.out",

	L"liquid.water",
	L"liquid.lavapop",
	L"liquid.lava",

	L"step.stone",
	L"step.wood",
	L"step.gravel",
	L"step.grass",
	L"step.metal",
	L"step.cloth",
	L"step.sand",

};*/