#pragma once


// 4J Stu - For non-splitscreen menus, default to this screen
#define DEFAULT_XUI_MENU_USER 0
#define MULTITHREAD_ENABLE
#define MAX_CAPENAME_SIZE 32
#define MAX_BANNERNAME_SIZE 32
#define MAX_TMSFILENAME_SIZE 40
#define MAX_TYPE_SIZE 32
#define MAX_EXTENSION_TYPES 3

#ifdef __PSVITA__
#define MAX_LOCAL_PLAYERS 1
#else
#define MAX_LOCAL_PLAYERS 4
#endif

// 4J Stu - Required for sentient reporting of whether the volume level has been changed or not
#define DEFAULT_VOLUME_LEVEL 100

#define GAME_HOST_OPTION_BITMASK_DIFFICULTY			0x00000003 // 0 - 3
#define GAME_HOST_OPTION_BITMASK_FRIENDSOFFRIENDS	0x00000004
#define GAME_HOST_OPTION_BITMASK_GAMERTAGS			0x00000008
#define GAME_HOST_OPTION_BITMASK_GAMETYPE			0x00000030
#define GAME_HOST_OPTION_BITMASK_LEVELTYPE			0x00000040
#define GAME_HOST_OPTION_BITMASK_STRUCTURES			0x00000080
#define GAME_HOST_OPTION_BITMASK_BONUSCHEST			0x00000100
#define GAME_HOST_OPTION_BITMASK_BEENINCREATIVE		0x00000200
#define GAME_HOST_OPTION_BITMASK_PVP				0x00000400
#define GAME_HOST_OPTION_BITMASK_TRUSTPLAYERS		0x00000800
#define GAME_HOST_OPTION_BITMASK_TNT				0x00001000
#define GAME_HOST_OPTION_BITMASK_FIRESPREADS		0x00002000
#define GAME_HOST_OPTION_BITMASK_HOSTFLY			0x00004000
#define GAME_HOST_OPTION_BITMASK_HOSTHUNGER			0x00008000
#define GAME_HOST_OPTION_BITMASK_HOSTINVISIBLE		0x00010000
#define GAME_HOST_OPTION_BITMASK_BEDROCKFOG			0x00020000
#define GAME_HOST_OPTION_BITMASK_DISABLESAVE		0x00040000
#define GAME_HOST_OPTION_BITMASK_NOTOWNER			0x00080000
#define GAME_HOST_OPTION_BITMASK_WORLDSIZE			0x00700000 // 3 bits, 5 values (unset(0), classic(1), small(2), medium(3), large(4))
#define GAME_HOST_OPTION_BITMASK_MOBGRIEFING		0x00800000
#define GAME_HOST_OPTION_BITMASK_KEEPINVENTORY		0x01000000
#define GAME_HOST_OPTION_BITMASK_DOMOBSPAWNING		0x02000000
#define GAME_HOST_OPTION_BITMASK_DOMOBLOOT			0x04000000
#define GAME_HOST_OPTION_BITMASK_DOTILEDROPS		0x08000000
#define GAME_HOST_OPTION_BITMASK_NATURALREGEN		0x10000000
#define GAME_HOST_OPTION_BITMASK_DODAYLIGHTCYCLE	0x20000000
#define GAME_HOST_OPTION_BITMASK_ALL				0xFFFFFFFF

#define GAME_HOST_OPTION_BITMASK_WORLDSIZE_BITSHIFT	20

enum EGameHostOptionWorldSize
{
	e_worldSize_Unknown = 0,
	e_worldSize_Classic,
	e_worldSize_Small,
	e_worldSize_Medium,
	e_worldSize_Large
};


#ifdef _XBOX
#define PROFILE_VERSION_1 1
#define PROFILE_VERSION_2 2
#define PROFILE_VERSION_3 3
#define PROFILE_VERSION_4 4
#define PROFILE_VERSION_5 6
#define PROFILE_VERSION_6 7
#define PROFILE_VERSION_7 8
#endif
#define PROFILE_VERSION_8 10
#define PROFILE_VERSION_9 11

#define PROFILE_VERSION_10 12

// 4J-JEV: New Statistics and Achievements for 'NexGen' platforms.
#define PROFILE_VERSION_11 13

// Java 1.6.4
#define PROFILE_VERSION_12 14

#define PROFILE_VERSION_CURRENT PROFILE_VERSION_12

#define MAX_FAVORITE_SKINS	10 // these are stored in the profile data so keep it small





// defines for game settings - uiBitmaskValues

#define GAMESETTING_CLOUDS								0x00000001
#define GAMESETTING_ONLINE								0x00000002
#define GAMESETTING_INVITEONLY							0x00000004
#define GAMESETTING_FRIENDSOFFRIENDS					0x00000008
#define GAMESETTING_DISPLAYUPDATEMSG					0x00000030
#define GAMESETTING_BEDROCKFOG							0x00000040
#define GAMESETTING_DISPLAYHUD							0x00000080
#define GAMESETTING_DISPLAYHAND							0x00000100
#define GAMESETTING_CUSTOMSKINANIM						0x00000200
#define GAMESETTING_DEATHMESSAGES						0x00000400
#define GAMESETTING_UISIZE								0x00001800
#define GAMESETTING_UISIZE_SPLITSCREEN					0x00006000
#define GAMESETTING_ANIMATEDCHARACTER					0x00008000
#define GAMESETTING_PS3EULAREAD							0x00010000
#define GAMESETTING_PSVITANETWORKMODEADHOC				0x00020000


// defines for languages

#define MINECRAFT_LANGUAGE_DEFAULT						0x00
#define MINECRAFT_LANGUAGE_ENGLISH						0x01
#define MINECRAFT_LANGUAGE_JAPANESE						0x02
#define MINECRAFT_LANGUAGE_GERMAN						0x03
#define MINECRAFT_LANGUAGE_FRENCH						0x04
#define MINECRAFT_LANGUAGE_SPANISH						0x05
#define MINECRAFT_LANGUAGE_ITALIAN						0x06
#define MINECRAFT_LANGUAGE_KOREAN						0x07
#define MINECRAFT_LANGUAGE_TCHINESE						0x08
#define MINECRAFT_LANGUAGE_PORTUGUESE					0x09
#define MINECRAFT_LANGUAGE_BRAZILIAN					0x0A
#define MINECRAFT_LANGUAGE_RUSSIAN						0x0B
#define MINECRAFT_LANGUAGE_DUTCH						0x0C
#define MINECRAFT_LANGUAGE_FINISH						0x0D
#define MINECRAFT_LANGUAGE_SWEDISH						0x0E
#define MINECRAFT_LANGUAGE_DANISH						0x0F
#define MINECRAFT_LANGUAGE_NORWEGIAN					0x10
#define MINECRAFT_LANGUAGE_POLISH						0x11
#define MINECRAFT_LANGUAGE_TURKISH						0x12
#define MINECRAFT_LANGUAGE_LATINAMERICANSPANISH			0x13
#define MINECRAFT_LANGUAGE_GREEK						0x14


 /* Match these

 const int XC_LANGUAGE_ENGLISH							=1;
 const int XC_LANGUAGE_JAPANESE							=2;
 const int XC_LANGUAGE_GERMAN							=3;
 const int XC_LANGUAGE_FRENCH							=4;
 const int XC_LANGUAGE_SPANISH							=5;
 const int XC_LANGUAGE_ITALIAN							=6;
 const int XC_LANGUAGE_KOREAN							=7;
 const int XC_LANGUAGE_TCHINESE							=8;
 const int XC_LANGUAGE_PORTUGUESE						=9;
 const int XC_LANGUAGE_BRAZILIAN						=10;
 const int XC_LANGUAGE_RUSSIAN							=11;
 const int XC_LANGUAGE_DUTCH							=12;
 const int XC_LANGUAGE_FINISH							=13;
 const int XC_LANGUAGE_SWEDISH							=14;
 const int XC_LANGUAGE_DANISH							=15;
 const int XC_LANGUAGE_NORWEGIAN						=16;
 const int XC_LANGUAGE_POLISH							=17;
 const int XC_LANGUAGE_TURKISH							=18;
 const int XC_LANGUAGE_LATINAMERICANSPANISH				=19;
 const int XC_LANGUAGE_GREEK							=20;
 */
