
#pragma once


#define VER_PRODUCTMAJORVERSION     0
#define VER_PRODUCTMINORVERSION     0

// This goes up with each build
// 4J-JEV: This value is extracted with a regex so it can be placed as the version in the AppX manifest on Durango.
#define VER_PRODUCTBUILD            560
// This goes up if there is any change to network traffic or code in a build
#define VER_NETWORK		            560
#define VER_PRODUCTBUILD_QFE        0

#define VER_FILEVERSION_STRING       "1.6"
#define VER_PRODUCTVERSION_STRING    VER_FILEVERSION_STRING
#define VER_FILEVERSION_STRING_W     L"1.6"
#define VER_PRODUCTVERSION_STRING_W  VER_FILEVERSION_STRING_W
#define VER_FILEBETA_STR         ""
#undef VER_FILEVERSION
#define VER_FILEVERSION          VER_PRODUCTMAJORVERSION, VER_PRODUCTMINORVERSION, VER_PRODUCTBUILD, VER_PRODUCTBUILD_QFE
#define VER_PRODUCTVERSION       VER_PRODUCTMAJORVERSION, VER_PRODUCTMINORVERSION, VER_PRODUCTBUILD, VER_PRODUCTBUILD_QFE

#if     (VER_PRODUCTBUILD < 10)
#define VER_FILEBPAD    "000"
#define VER_FILEBPAD_W L"000"
#elif   (VER_PRODUCTBUILD < 100)
#define VER_FILEBPAD    "00"
#define VER_FILEBPAD_W L"00"
#elif   (VER_PRODUCTBUILD < 1000)
#define VER_FILEBPAD    "0"
#define VER_FILEBPAD_W L"0"
#else
#define VER_FILEBPAD
#define VER_FILEBPAD_W
#endif

#define VER_WIDE_PREFIX(x) L##x

#define VER_FILEVERSION_STR2(x,y)   VER_FILEVERSION_STRING    "." VER_FILEBPAD  #x  "."  #y
#define VER_FILEVERSION_STR2_W(x,y) VER_FILEVERSION_STRING_W L"." VER_FILEBPAD_W VER_WIDE_PREFIX(#x) L"." VER_WIDE_PREFIX(#y)
#define VER_FILEVERSION_STR1(x,y)   VER_FILEVERSION_STR2(x, y)
#define VER_FILEVERSION_STR1_W(x,y) VER_FILEVERSION_STR2_W(x, y)

#undef VER_FILEVERSION_STR
#define VER_FILEVERSION_STR       VER_FILEVERSION_STR1(VER_PRODUCTBUILD, VER_PRODUCTBUILD_QFE)
#define VER_PRODUCTVERSION_STR    VER_FILEVERSION_STR1(VER_PRODUCTBUILD, VER_PRODUCTBUILD_QFE)

#define VER_FILEVERSION_STR_W     VER_FILEVERSION_STR1_W(VER_PRODUCTBUILD, VER_PRODUCTBUILD_QFE)
#define VER_PRODUCTVERSION_STR_W  VER_FILEVERSION_STR1_W(VER_PRODUCTBUILD, VER_PRODUCTBUILD_QFE)

#if     (VER_PRODUCTBUILD_QFE >= 256)
#error  "QFE number cannot exceed 255"
#endif



